name: Actions Workflow

on:
  push:

jobs: 
  setup-build:
    runs-on: 
      - self-hosted
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configuring
        run: ./configure
      - name: Make 
        run: make
      - name: Echo "Hello world"
        run: ./lessecho "Hello world"
      - name: zipping
        run: | 
          tar -czf Test.tar.gz charset.c
          rsync -avzh Test.tar.gz luis@192.168.15.123:/home/luis