name: Actions Workflow

on:
  push:
  schedule: 
   - cron: '20 15 * * *'

jobs: 
  setup-build:
    runs-on: 
      - self-hosted
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuring
        run: ./configure

      - name: Make 
        run: make

      - name: Echo "Hello world"
        run: ./lessecho "Hello world"
        
      - name: PWD
        run: 
          pwd
      - name: zipping
        run: | 
          cd /home/luis/actions-runner/_work/Hosted
          rm Less.tar.gz
          tar -czvf Less.tar.gz --exclude='.git' Hosted
      - name: Uploading
        #run: |
          #cd /home/luis/actions-runner/_work/Hosted
          #rsync -avzh Less.tar.gz luis@192.168.15.107:/home/luis

        run: |
          docker ps


