name: Actions Workflow

on:
  push:

jobs: 
  setup-build:
    runs-on: 
      - self-hosted
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configuring
        run: ./configure
      - name: Make 
        run: make
      - name: Echo "Hello world"
        run: ./lessecho "Hello world"
      - name: PWD
        run: 
          pwd
      - name: zipping
        run: | 
          cd /home/luis/actions-runner/_work/Hosted
          tar -czvf Less.tar.gz --exclude='.git' --exclude='Less.tar.gz' Hosted
      - name: Uploading
        run: |
          cd /home/luis/actions-runner/_work/Hosted
          rsync -avzh Less.tar.gz luis@192.168.15.107:/home/luis